server:
  port: 9017
  error:
    whitelabel:
      enabled: false
    path: /sendError
    include-exception: true
    include-stacktrace: on_param

spring:
  application:
    name: daily-tracker-console
  bean info:
    ignore: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    log-startup-info: on
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: /tmp
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

logging:
  level:
    com.beta.daily.tracker: INFO
    org.springframework.security: ERROR
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ERROR
    org.springframework.web.servlet.DispatcherServlet: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.springframework: ERROR
    web: info

feign:
  client :
    config :
      default:
        connectTimeout: 60000
        readTimeout : 60000
  compression:
    request:
      enabled: true
      mime-types: application/json
    response:
      enabled: true
      useGzipDecoder: true